using Microsoft.CodeAnalysis;
using ParaSmellerCore.Diagnostics;
using ParaSmellerCore.Reporters;

namespace ParaSmellerAnalyzer.Analyzer
{
    public static class Rules
    {
        public static readonly DiagnosticDescriptor ExplicitThreadsRule = new DiagnosticDescriptor(ExplicitThreadsReporter.DiagnosticId, ExplicitThreadsReporter.Title, ExplicitThreadsReporter.MessageFormat, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, ExplicitThreadsReporter.Description);
        public static readonly DiagnosticDescriptor FinalizerSynchronizationUsageRule = new DiagnosticDescriptor(FinalizerReporter.FinalizerSynchronizationDiagnosticId, FinalizerReporter.Title, FinalizerReporter.MessageFormatFinalizerSynchronization, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, FinalizerReporter.Description);
        public static readonly DiagnosticDescriptor RuleFireAndForgetCallRule = new DiagnosticDescriptor(FireAndForgetReporter.FireAndForgetCallId, FireAndForgetReporter.Title, FireAndForgetReporter.MessageFormatFireAndForghet, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, FireAndForgetReporter.Description);
        public static readonly DiagnosticDescriptor HalfSynchronizedRule = new DiagnosticDescriptor(HalfSynchronizedReporter.HalfSynchronizedChildDiagnosticId, HalfSynchronizedReporter.Title, HalfSynchronizedReporter.MessageFormatHalfSynchronized, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, HalfSynchronizedReporter.Description);
        public static readonly DiagnosticDescriptor UnsynchronizedPropertyRule = new DiagnosticDescriptor(HalfSynchronizedReporter.UnsynchronizedPropertyId, HalfSynchronizedReporter.Title, HalfSynchronizedReporter.MessageFormatUnsychronizedProperty, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, HalfSynchronizedReporter.Description);
        public static readonly DiagnosticDescriptor MonitorPulseRule = new DiagnosticDescriptor(MonitorOrWaitSignalReporter.MonitorPulseDiagnosticId, MonitorOrWaitSignalReporter.Title, MonitorOrWaitSignalReporter.MessageFormatPulse, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, MonitorOrWaitSignalReporter.Description);
        public static readonly DiagnosticDescriptor MonitorIfRule = new DiagnosticDescriptor(MonitorOrWaitSignalReporter.MonitorIfConditionDiagnosticId, MonitorOrWaitSignalReporter.Title, MonitorOrWaitSignalReporter.MessageFormatIf, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, MonitorOrWaitSignalReporter.Description);
        public static readonly DiagnosticDescriptor NestedLockingOneRule = new DiagnosticDescriptor(NestedSynchronizedMethodClassReporter.NestedLockingDiagnosticId, NestedSynchronizedMethodClassReporter.Title, NestedSynchronizedMethodClassReporter.MessageFormat, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, NestedSynchronizedMethodClassReporter.Description);
        public static readonly DiagnosticDescriptor NestedLockingTwoRule = new DiagnosticDescriptor(NestedSynchronizedMethodClassReporter.NestedLockingDiagnosticId2, NestedSynchronizedMethodClassReporter.Title, NestedSynchronizedMethodClassReporter.MessageFormat, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, NestedSynchronizedMethodClassReporter.Description);
        public static readonly DiagnosticDescriptor PrivateAsyncRule = new DiagnosticDescriptor(OverAsynchronyReporter.DiagnosticId, OverAsynchronyReporter.Title, OverAsynchronyReporter.MessageFormat, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, OverAsynchronyReporter.Description);
        public static readonly DiagnosticDescriptor NestedAsyncRule = new DiagnosticDescriptor(OverAsynchronyReporter.DiagnosticIdNestedAsync, OverAsynchronyReporter.Title, OverAsynchronyReporter.MessageFormatNestedAsync, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, OverAsynchronyReporter.Description);
        public static readonly DiagnosticDescriptor PrimitiveSynchronizationUsageRule = new DiagnosticDescriptor(PrimitiveSynchronizationReporter.PrimitiveSynchronizationDiagnosticId, PrimitiveSynchronizationReporter.Title, PrimitiveSynchronizationReporter.MessageFormatPrimitiveSynchronization, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, PrimitiveSynchronizationReporter.Description);
        public static readonly DiagnosticDescriptor TentativelyResourceReferenceRule = new DiagnosticDescriptor(TentativelyResourceReferenceReporter.DiagnosticId, TentativelyResourceReferenceReporter.Title, TentativelyResourceReferenceReporter.MessageFormatTentativelyResourceReference, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, TentativelyResourceReferenceReporter.Description);
        public static readonly DiagnosticDescriptor TapirRule = new DiagnosticDescriptor(TapirReporter.DiagnosticId, TapirReporter.Title, TapirReporter.MessageFormat, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, TapirReporter.Description);
        public static readonly DiagnosticDescriptor WaitingConditionsTasksRule = new DiagnosticDescriptor(WaitingConditionsTasksReporter.WaitingConditionsTasksDiagnosticId, WaitingConditionsTasksReporter.Title, WaitingConditionsTasksReporter.MessageFormat, DiagnosticCategory.Synchronization, DiagnosticSeverity.Warning, true, WaitingConditionsTasksReporter.Description);
    }
}
